name: CI

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: dotnet build FNA
      run: |
        dotnet build -c Debug ./src/FNA.csproj
        dotnet build -c Release ./src/FNA.csproj

